# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog-set-time.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogUI(object):
    def setupUi(self, dialogUI):
        dialogUI.setObjectName("dialogUI")
        dialogUI.resize(501, 306)
        dialogUI.setStyleSheet("QFrame{\n"
"    background-color: rgb(217, 217, 217);\n"
"}\n"
"")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(dialogUI)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dialogFrame = QtWidgets.QFrame(dialogUI)
        self.dialogFrame.setStyleSheet("QFrame{\n"
"    border-radius:30px;\n"
"}\n"
"QPushButton{\n"
"    color:grey;\n"
"    border-style: solid;\n"
"    border-width:2px;\n"
"    border-color: #00557f;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color:#00FFFF;\n"
"    border-style: solid;\n"
"    border-width:2px;\n"
"    border-color: #00FFFF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"#Opps{\n"
"    \n"
"    color: rgb(85, 255, 127);\n"
"}\n"
"#No_Internet{\n"
"    \n"
"    color: rgb(170, 255, 255);\n"
"}\n"
"")
        self.dialogFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dialogFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dialogFrame.setObjectName("dialogFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dialogFrame)
        self.verticalLayout_3.setContentsMargins(30, -1, 30, 15)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.feedingTimeTitle = QtWidgets.QLabel(self.dialogFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.feedingTimeTitle.setFont(font)
        self.feedingTimeTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.feedingTimeTitle.setObjectName("feedingTimeTitle")
        self.verticalLayout_3.addWidget(self.feedingTimeTitle)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.firstSchedVLayout = QtWidgets.QVBoxLayout()
        self.firstSchedVLayout.setSpacing(0)
        self.firstSchedVLayout.setObjectName("firstSchedVLayout")
        self.firstSchedTitle = QtWidgets.QLabel(self.dialogFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.firstSchedTitle.setFont(font)
        self.firstSchedTitle.setObjectName("firstSchedTitle")
        self.firstSchedVLayout.addWidget(self.firstSchedTitle)
        self.firstSchedTime = QtWidgets.QTimeEdit(self.dialogFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.firstSchedTime.setFont(font)
        self.firstSchedTime.setStyleSheet("QTimeEdit {\n"
"    background-color: transparent;\n"
"    color: #000;\n"
"    border: 3px solid rgb(25, 61, 77);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-size: 20px;\n"
"}")
        self.firstSchedTime.setAlignment(QtCore.Qt.AlignCenter)
        self.firstSchedTime.setObjectName("firstSchedTime")
        self.firstSchedVLayout.addWidget(self.firstSchedTime)
        self.verticalLayout.addLayout(self.firstSchedVLayout)
        self.secondSchedVLayout = QtWidgets.QVBoxLayout()
        self.secondSchedVLayout.setSpacing(0)
        self.secondSchedVLayout.setObjectName("secondSchedVLayout")
        self.secondSchedTitle = QtWidgets.QLabel(self.dialogFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.secondSchedTitle.setFont(font)
        self.secondSchedTitle.setObjectName("secondSchedTitle")
        self.secondSchedVLayout.addWidget(self.secondSchedTitle)
        self.secondSchedTime = QtWidgets.QTimeEdit(self.dialogFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.secondSchedTime.setFont(font)
        self.secondSchedTime.setStyleSheet("QTimeEdit {\n"
"    background-color: transparent;\n"
"    color: #000;\n"
"    border: 3px solid rgb(25, 61, 77);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-size: 20px;\n"
"}")
        self.secondSchedTime.setAlignment(QtCore.Qt.AlignCenter)
        self.secondSchedTime.setObjectName("secondSchedTime")
        self.secondSchedVLayout.addWidget(self.secondSchedTime)
        self.verticalLayout.addLayout(self.secondSchedVLayout)
        self.buttonHLayout = QtWidgets.QHBoxLayout()
        self.buttonHLayout.setSpacing(15)
        self.buttonHLayout.setObjectName("buttonHLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonHLayout.addItem(spacerItem)
        self.setTimeBtn = QtWidgets.QPushButton(self.dialogFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.setTimeBtn.setFont(font)
        self.setTimeBtn.setStyleSheet("QPushButton {\n"
"    background-color: #287194;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    border: none;\n"
"    padding: 3px 50px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1F5773;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #193D4D;\n"
"}\n"
"")
        self.setTimeBtn.setObjectName("setTimeBtn")
        self.buttonHLayout.addWidget(self.setTimeBtn)
        self.cancelTimeBtn = QtWidgets.QPushButton(self.dialogFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancelTimeBtn.setFont(font)
        self.cancelTimeBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color: #287194;\n"
"    padding: 5px 30px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #1F5773;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #193D4D;\n"
"}")
        self.cancelTimeBtn.setObjectName("cancelTimeBtn")
        self.buttonHLayout.addWidget(self.cancelTimeBtn)
        self.verticalLayout.addLayout(self.buttonHLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.dialogFrame)

        self.retranslateUi(dialogUI)
        QtCore.QMetaObject.connectSlotsByName(dialogUI)

    def retranslateUi(self, dialogUI):
        _translate = QtCore.QCoreApplication.translate
        dialogUI.setWindowTitle(_translate("dialogUI", "Dialog"))
        self.feedingTimeTitle.setText(_translate("dialogUI", "Feeding Time Schedule"))
        self.firstSchedTitle.setText(_translate("dialogUI", "First Feeding Schedule:"))
        self.secondSchedTitle.setText(_translate("dialogUI", "Second Feeding Schedule:"))
        self.setTimeBtn.setText(_translate("dialogUI", "SET"))
        self.cancelTimeBtn.setText(_translate("dialogUI", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogUI = QtWidgets.QDialog()
    ui = Ui_dialogUI()
    ui.setupUi(dialogUI)
    dialogUI.show()
    sys.exit(app.exec_())
